### ISSUE TITLE
Antenna position plot based on currently-filtered items in Session List View

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/antenna_plots_v2#11]
_If_ #7 turns out to be viable, this should be a "simple" matter of stacking the necessary plots up (based on the current Sessions in the table queryset), rendering the image, and 

This will require getting datashader and geoviews, etc installed into your alda env, which hopefully is fairly straightforward

**Comment by KaseyW31** [comment]
Yesterday, I set up a conda environment with alda dependencies and the data visualization packages (after some issues with PyPI). I found out how to access the queryset from the template, but I might try to stack the images from a different file (models/views/etc). I also spent time familiarizing myself with django, filters, tables, etc
