### ISSUE TITLE
Quest: Figure out how the Datashader NYC Taxi example works

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/antenna_plots_v2#14]
https://nyc-taxi.pyviz.demo.anaconda.com/dashboard

Specifically, where is it getting the data? Is it pre-loaded at the beginning, or fetched dynamically? How?

1. What are the dynamic (i.e. result in network requests) elements of the plot?
2. Where are the data coming from for each?

Use Firefox dev tools to analyze

**Comment by KaseyW31** [comment]
Some of the data is cached at the beginning, though most of it seems to be fetched dynamically. There's a websocket that could be receiving client requests to update the plot and sending back data. When I compare memory snapshots of before vs. after requests, an ArrayBuffer gains or loses several megabytes of data. Also, it looks like there's nothing in storage, but I could be misinterpreting that tab

1. Changing panel sliders and zooming/panning result in network requests. I think both the stamen map tiles and datashading are dynamic, but I'm not certain
2. It looks like the stamen map tiles are GET requests from a site/service containing the map png files (if they're not already cached), and the datapoints/shading could be received from the server and stored in the ArrayBuffer?
