### ISSUE TITLE
Plot all Antenna positions in Datashader

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/antenna_plots_v2#2]
The goal here is the same as GreenBankObservatory/antenna_plots_v2#3, but for _all_ Antenna data.

You should be able to read the data from `/home/scratch/tchamber/antenna_data/ant_pos_all_v2.parquet`. This will be your first time working with Parquet data -- you can read more about it [here](https://en.wikipedia.org/wiki/Apache_Parquet)

You'll need to install `pandas` and `pyarrow` into your Conda env.

Use [pd.read_parquet](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html) to load the data into a DataFrame. Your code should load only the columns that you need: right now, that's just `DMJD`, `RAJ2000`, and `DECJ2000`. Note that loading all columns and then deleting the extra ones is _not_ sufficient -- the unnecessary columns should never be loaded at all.

Produce a set of three images from this data using [datashader](datashader.org/) and attach them to this issue. Each image should use a different color map. You can read about color maps [here](https://colorcet.holoviz.org/). Select whatever three color maps you want -- up to you! Explore the site further for full lists of all available color maps.

Images should be plotted at a resolution of 2000x1000 pixels

Your script should print out some debug info:

1. How long it takes to:
    - load the parquet file into the DataFrame
    - render the DataFrame using datashader
    - render the shaded image to a bitmap
2. How many total rows are in the file
3. The total sizes of the following items, using the `format_bytes` function below:
    - The input file
    - The DataFrame in memory

```py
def format_bytes(num_bytes: int):
    """Format the given number of bytes using SI unit suffixes

    https://en.wikipedia.org/wiki/Byte#Multiple-byte_units
    """
    power = 1024
    n = 0
    power_labels = {0: "B", 1: "KiB", 2: "MiB", 3: "GiB", 4: "TiB", 5: "PiB", 6: "EiB"}
    while num_bytes > power:
        num_bytes /= power
        n += 1
    try:
        return f"{num_bytes:,.2f} {power_labels[n]}"
    except IndexError:
        # If we don't have a power label, just return the raw bytes with the appropriate suffix
        return f"{num_bytes:,.2f} B"
```

**Comment by KaseyW31** [comment]
![Image](https://github.com/GreenBankObservatory/antenna_plots_v2/assets/115895250/56f2081f-a8d8-411c-ac0c-ae642442d9b0)
![Image](https://github.com/GreenBankObservatory/antenna_plots_v2/assets/115895250/40cc287b-36cd-4c56-93f7-2b9477bb8849)
![Image](https://github.com/GreenBankObservatory/antenna_plots_v2/assets/115895250/4c9257f8-17a9-46d9-831f-c22d4a1caed9)

**Comment by tchamberlin** [comment]
Awesome! These look correct, except for two things:

1. These appear to be flipped horizontally from what I'd expect
2. The bottom ~40 degrees are empty, but should still be displayed

**Comment by KaseyW31** [comment]
Hmm
- For the horizontal flipping, I'll work on fixing the data wrapping
- I'm still trying to figure out how to display the bottom portion -- I tried adding the canvas x/y ranges, but the data is already converted into meters(?) so I'll try adjusting earlier operations

**Comment by tchamberlin** [comment]
1. Looking back at old code, I think I used a wrap angle of `360`. So hopefully that's the only difference
2. I think what I did was put the boundaries/extents in a dataframe, then project that, then use the projected values as the final extents

**Comment by KaseyW31** [comment]
Thanks! I think I fixed it?

![Image](https://github.com/GreenBankObservatory/antenna_plots_v2/assets/115895250/6f2648b6-81a3-435e-84c9-9c3a0aa45984)
![Image](https://github.com/GreenBankObservatory/antenna_plots_v2/assets/115895250/681cc460-9f6b-4967-b637-1d936581ebc3)
![Image](https://github.com/GreenBankObservatory/antenna_plots_v2/assets/115895250/23d12b62-8d33-4310-bef8-7f26bea45bd7)

**Comment by tchamberlin** [comment]
That looks right!
