### ISSUE TITLE
Antenna Data in Datashader

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/antenna_plots_v2#3]
Plot the same Antenna data from GreenBankObservatory/summer_onboarding_2023#2 using datashader instead of matplotlib. 

This can be done in a Jupyter notebook, or in a "simple" Python script where you write an image file to disk. For the latter option, you can use the Image API from Datashader: https://datashader.org/api.html#transfer-functions

Attach the image you produce to this issue once you're done

**Comment by KaseyW31** [comment]
- Got up to reading in the FITS table as a Pandas dataframe, plotting the data as an image, and plotting using Holoviews (using a Jupyter notebook)
- Currently trying to figure out how to plot with a Mollweide projection -- I finished downloading Geoviews and will be trying to use it along with cartopy
- Was also having trouble with customizing axis labels, and I'll be working on it today
