### ISSUE TITLE
Static antenna position plot on Session Detail

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/antenna_plots_v2#6]
Blocked by [Alda sandbox setup](https://github.com/GreenBankObservatory/summer_onboarding_2023/issues/6)

Similar to #5, but instead of showing _all_ antenna data, we just want the data for a given Session. For example, https://gbtarchive-beta.gb.nrao.edu/disk/sessions/AGBT17A_304_03/ should display only the antenna positions recorded during all scans from `AGBT17A_304_03`

This will require a "database" of per-session antenna position plots -- I will provide this. Your code can expect to find a given Session's antenna plot at static URL `'images/antenna_positions/session/{{session_name}}.jpg'`. So, in the above example, it would load  `STATIC_ROOT + '/images/antenna_positions/session/AGBT17A_304_03.jpg'`

**Comment by KaseyW31** [comment]
- Wrote a script to loop through my original script (that generates a map image for a single parquet file) for a list of paths. In hindsight, I would just modify my original script to speed things to avoid importing packages at every iteration
- Had to look up static tags in Django and how to use them with variables

**Comment by tchamberlin** [comment]
TODO: Remove images from git, squash/merge, done

**Comment by KaseyW31** [comment]
I think I removed all the images, is it ok to squash/merge?
